"""ORM model for the `transaction_ocr_extraction` table (design D117).

Separate module from `app/transactions/models.py` — mirroring
`app/admin/models.py`'s convention for a tightly-scoped, 1:1-related table
(`PlatformAdmin` keyed on `app_user.id`) — because this table belongs to the
Phase 9 OCR domain, not to core transaction management, even though it FKs
into `Transaction`. Column shape matches migration `0012_ocr_drafts.py`'s
hand-written DDL exactly; that migration is NOT autogenerated from this
class (design's "no ORM autogeneration" convention, see
`migrations/env.py`), so the two must be kept in sync by hand and are
cross-checked by `backend/tests/migrations/test_0012.py`.

`raw_response` holds the verbatim Textract response, which contains real
receipt contents. It is never logged and never included in any API
response (design D117's privacy rule) — enforced by later units, not this
one; this class only shapes the column.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import CheckConstraint, Date, ForeignKey, Numeric, SmallInteger, Text
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class TransactionOcrExtraction(Base):
    """One row per draft transaction's OCR attempt. `transaction_id` is the
    PRIMARY KEY directly (design D117, mirroring `PlatformAdmin.user_id`) —
    the 1:1 relationship with `Transaction` is structural, not a uniqueness
    constraint someone must remember. `ON CONFLICT (transaction_id) DO
    UPDATE` upserts this row on re-processing (design D127)."""

    __tablename__ = "transaction_ocr_extraction"
    __table_args__ = (
        CheckConstraint(
            "status IN ('succeeded', 'failed')",
            name="ck_ocr_extraction_status",
        ),
        CheckConstraint(
            "(status = 'failed') = (failure_reason IS NOT NULL)",
            name="ck_ocr_extraction_failure_reason",
        ),
        CheckConstraint(
            "failure_reason IS NULL OR failure_reason IN "
            "('provider_unavailable', 'unreadable_document', 'no_receipt_detected')",
            name="ck_ocr_extraction_failure_reason_domain",
        ),
    )

    transaction_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.transaction.id", ondelete="CASCADE"),
        primary_key=True,
    )
    status: Mapped[str] = mapped_column(Text, nullable=False)
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    extracted_amount: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    extracted_occurred_on: Mapped[date | None] = mapped_column(Date, nullable=True)
    extracted_vendor_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Advisory only — never applied to the confirmed transaction (design
    # D118); the app has no per-transaction currency column at all.
    extracted_currency: Mapped[str | None] = mapped_column(Text, nullable=True)
    field_confidence: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    raw_response: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    provider: Mapped[str] = mapped_column(Text, nullable=False, server_default="textract")
    attempt_count: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default="1")
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
