"""ORM model for the `platform-admin` domain (design D97).

Declarative model on the shared `app.db.Base` registry, matching
`app/workspace/models.py`'s convention. Column shape matches migration
`0008_platform_admin.py`'s hand-written DDL exactly — that migration is
NOT autogenerated from this class (design's "no ORM autogeneration"
convention, see `migrations/env.py`), so the two must be kept in sync by
hand and are cross-checked by `backend/tests/migrations/test_0008.py`.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, Text
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class PlatformAdmin(Base):
    """One row per platform administrator. `user_id` is the PRIMARY KEY
    directly (design D97) — "at most one grant per user" is a structural
    fact, not a uniqueness constraint someone must remember."""

    __tablename__ = "platform_admin"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="CASCADE"),
        primary_key=True,
    )
    granted_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    # Nullable with ON DELETE SET NULL — never CASCADE (design D97): NULL
    # means bootstrap (no human granter), and a granter's own account
    # changes must never erase the provenance of a grant they made.
    granted_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="SET NULL"),
        nullable=True,
    )
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
