"""End-to-end happy path: successful login -> JWT issued -> `/api/me`
returns 200 -> refresh rotates the cookie pair -> logout revokes it.

Exercises the fully wired router through httpx `ASGITransport` (no live
server process), per the design's testing strategy. Runs against a REAL,
ephemeral PostgreSQL server (see `conftest.py` `auth_db_sessionmaker`),
because `/api/me` returning 200 depends on the user actually having been
persisted by the callback handler, not just on token verification.

This complements the adversarial RED cases in the other `tests/auth/*`
modules: those prove each individual rejection; this proves the
legitimate path still works end to end.
"""

from __future__ import annotations

import time
from types import SimpleNamespace
from urllib.parse import parse_qs, urlparse

import httpx
import jwt
import pytest
from cryptography.hazmat.primitives.asymmetric import rsa
from httpx import ASGITransport, AsyncClient

from app.config import get_settings
from app.db import get_db
from app.main import create_app


@pytest.fixture
def rsa_keypair():
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    return private_key, private_key.public_key()


def _make_id_token(private_key, *, google_sub: str, email: str, nonce: str) -> str:
    settings = get_settings()
    now = int(time.time())
    payload = {
        "iss": settings.google_issuer,
        "aud": settings.google_client_id,
        "sub": google_sub,
        "email": email,
        "nonce": nonce,
        "iat": now,
        "exp": now + 3600,
    }
    return jwt.encode(payload, private_key, algorithm="RS256", headers={"kid": "test-kid"})


def _app_with_real_db(auth_db_sessionmaker):
    app = create_app()

    def override_get_db():
        session = auth_db_sessionmaker()
        try:
            yield session
        finally:
            session.close()

    app.dependency_overrides[get_db] = override_get_db
    return app


async def test_me_without_any_cookie_is_unauthorized(auth_db_sessionmaker) -> None:
    app = _app_with_real_db(auth_db_sessionmaker)
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="https://test") as client:
        response = await client.get("/api/me")

    assert response.status_code == 401


async def test_full_login_flow_issues_jwt_and_reaches_me(
    monkeypatch: pytest.MonkeyPatch, rsa_keypair, auth_db_sessionmaker
) -> None:
    private_key, public_key = rsa_keypair
    monkeypatch.setenv("WALLEZA_GOOGLE_CLIENT_ID", "test-client-id")
    get_settings.cache_clear()

    monkeypatch.setattr(
        "app.security._get_google_jwks_client",
        lambda: SimpleNamespace(get_signing_key_from_jwt=lambda _t: SimpleNamespace(key=public_key)),
    )

    app = _app_with_real_db(auth_db_sessionmaker)
    transport = ASGITransport(app=app)

    # Cookies set by this app are all `Secure` (design D9 — same-origin,
    # HTTPS-only in production), so the test client must use an https://
    # base_url or a real client would never resend them either.
    async with AsyncClient(transport=transport, base_url="https://test") as client:
        # Step 1: GET /api/auth/login sets the pkce_state cookie and
        # redirects to Google with `state` and `nonce` query parameters.
        login_response = await client.get("/api/auth/login", follow_redirects=False)
        assert login_response.status_code == 302
        assert client.cookies.get("pkce_state")

        location = login_response.headers["location"]
        assert location.startswith("https://accounts.google.com/")
        query = parse_qs(urlparse(location).query)
        state = query["state"][0]
        nonce = query["nonce"][0]

        # The mocked Google token endpoint can only be wired up once the
        # real `nonce` generated by `/api/auth/login` is known — a real
        # Google would echo this same value back inside the ID token.
        id_token = _make_id_token(
            private_key, google_sub="google-sub-happy", email="happy@example.com", nonce=nonce
        )

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200,
                json={
                    "access_token": "google-access-token",
                    "id_token": id_token,
                    "token_type": "Bearer",
                    "expires_in": 3600,
                },
            )

        monkeypatch.setattr("app.auth.google._default_transport", httpx.MockTransport(handler))

        # Step 2: simulate Google's redirect back to our callback with a
        # matching `state` and an authorization code.
        callback_response = await client.get(
            "/api/auth/callback",
            params={"code": "auth-code-happy-path", "state": state},
            follow_redirects=False,
        )
        assert callback_response.status_code == 302
        assert callback_response.headers["location"] == "/"
        access_cookie = client.cookies.get("walleza_access")
        refresh_cookie = client.cookies.get("walleza_refresh")
        assert access_cookie
        assert refresh_cookie

        # Step 3: the issued access-token cookie reaches the guarded
        # /api/me endpoint and resolves the persisted identity.
        me_response = await client.get("/api/me")
        assert me_response.status_code == 200
        body = me_response.json()
        assert body["email"] == "happy@example.com"

        # Step 4: refreshing rotates both cookies.
        refresh_response = await client.post("/api/auth/refresh")
        assert refresh_response.status_code == 204
        assert client.cookies.get("walleza_refresh") != refresh_cookie

        # Step 5: logout revokes the family and clears the cookies.
        logout_response = await client.post("/api/auth/logout")
        assert logout_response.status_code == 204

    get_settings.cache_clear()


async def test_full_login_flow_rejects_id_token_with_mismatched_nonce(
    monkeypatch: pytest.MonkeyPatch, rsa_keypair, auth_db_sessionmaker
) -> None:
    """Design D7: the ID token's `nonce` claim must match the value
    generated by `/api/auth/login` and round-tripped through the signed
    `pkce_state` cookie. A Google response carrying a different `nonce`
    (e.g. a substituted/replayed ID token from a different auth attempt)
    must fail the callback, not just the isolated verification helper."""
    private_key, public_key = rsa_keypair
    monkeypatch.setenv("WALLEZA_GOOGLE_CLIENT_ID", "test-client-id")
    get_settings.cache_clear()

    monkeypatch.setattr(
        "app.security._get_google_jwks_client",
        lambda: SimpleNamespace(get_signing_key_from_jwt=lambda _t: SimpleNamespace(key=public_key)),
    )

    app = _app_with_real_db(auth_db_sessionmaker)
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="https://test") as client:
        login_response = await client.get("/api/auth/login", follow_redirects=False)
        assert login_response.status_code == 302

        location = login_response.headers["location"]
        state = parse_qs(urlparse(location).query)["state"][0]

        # A different (wrong) nonce than the one this login actually
        # generated — simulates a substituted or replayed ID token.
        id_token = _make_id_token(
            private_key,
            google_sub="google-sub-nonce-mismatch",
            email="nonce-mismatch@example.com",
            nonce="a-completely-different-nonce",
        )

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200,
                json={
                    "access_token": "google-access-token",
                    "id_token": id_token,
                    "token_type": "Bearer",
                    "expires_in": 3600,
                },
            )

        monkeypatch.setattr("app.auth.google._default_transport", httpx.MockTransport(handler))

        callback_response = await client.get(
            "/api/auth/callback",
            params={"code": "auth-code-nonce-mismatch", "state": state},
            follow_redirects=False,
        )
        assert callback_response.status_code == 401
        assert not client.cookies.get("walleza_access")

    get_settings.cache_clear()
