"""Alembic environment.

Resolves the DDL connection string from `app.config.get_settings()`
(`resolved_migrations_database_url`) instead of a static `sqlalchemy.url`
in `alembic.ini`. This is load-bearing per design D2/D3: migrations MUST
run through the direct/session-mode `:5432` connection, never through the
Supavisor transaction pooler (`:6543`) that `app/db.py` uses at runtime,
because transaction-pooling mode forbids server-side prepared statements
and behaves differently under DDL/locks.

There is no SQLAlchemy declarative model layer yet (Phase 2 only built
`app/config.py`, `app/db.py`, `app/security.py`, `app/main.py`,
`app/handler.py` — no ORM models), so `target_metadata` is `None` and every
revision is a hand-written, explicit `op.create_table(...)` script (see
`migrations/versions/0001_baseline.py`), not an autogenerated diff.
"""

from logging.config import fileConfig

import sqlalchemy as sa
from alembic import context
from sqlalchemy import engine_from_config, pool

from app.config import get_settings

# Alembic Config object, giving access to values within alembic.ini.
config = context.config

# Interpret the config file for Python logging (loggers, handlers, ...).
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# No ORM models to autogenerate against in this phase — every revision is
# written by hand.
target_metadata = None

# Alembic owns a private `app` schema (design's Technical Approach), so its
# own bookkeeping table (`alembic_version`) lives there too instead of the
# default `public` — keeping our entire footprint, framework table included,
# out of `public`/PostgREST's anon-key-exposed default schema.
VERSION_TABLE_SCHEMA = "app"


def get_url() -> str:
    """Resolve the direct DDL connection string at run time, not import time.

    Deferred until a migration actually runs (rather than read once at
    module import) so tests can point migrations at a throwaway database
    via `WALLEZA_MIGRATIONS_DATABASE_URL` and `get_settings.cache_clear()`
    without needing to reload this module.
    """
    return get_settings().resolved_migrations_database_url


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL, no live connection)."""
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table_schema=VERSION_TABLE_SCHEMA,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a real DDL connection."""
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = get_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # Alembic creates its own `alembic_version` bookkeeping table inside
        # `VERSION_TABLE_SCHEMA` before running any revision, so that schema
        # must already exist — it cannot wait for revision 0001's own
        # `CREATE SCHEMA IF NOT EXISTS app` to run first.
        connection.execute(sa.text(f"CREATE SCHEMA IF NOT EXISTS {VERSION_TABLE_SCHEMA}"))
        connection.commit()

        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table_schema=VERSION_TABLE_SCHEMA,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
