"""ORM model for the `audit-log` domain (design D102).

Declarative model on the shared `app.db.Base` registry, matching
`app/workspace/models.py`/`app/admin/models.py`'s convention. Column shape
matches migration `0011_audit_log.py`'s hand-written DDL exactly — that
migration is NOT autogenerated from this class, so the two must be kept in
sync by hand and are cross-checked by `backend/tests/migrations/test_0011.py`.

Append-only (spec "Append-Only Storage" requirement): this module
deliberately defines no update/delete helper, and no other module in this
codebase updates or deletes an `AuditLog` row — that absence IS the
guarantee, not a runtime check.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

import sqlalchemy as sa
from sqlalchemy import ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    # Nullable with ON DELETE SET NULL — never CASCADE (design D102): an
    # audit row must outlive the deletion of the user it names.
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Snapshot boolean, not derived from the current `platform_admin` table
    # at read time — grants are revocable, so "was this person an admin
    # then?" would otherwise become unreconstructable after a revoke.
    actor_was_platform_admin: Mapped[bool] = mapped_column(sa.Boolean, nullable=False)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    target_type: Mapped[str] = mapped_column(Text, nullable=False)
    target_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    # Nullable with ON DELETE SET NULL — never CASCADE: platform-level
    # actions (grant admin, deactivate user) belong to no single
    # workspace, and a deleted workspace must not erase its own history.
    workspace_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.workspace.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Mapped under the Python attribute `metadata_` — `Base.metadata` is
    # SQLAlchemy's own reserved `MetaData` attribute on every declarative
    # model, so the DB column name `metadata` cannot also be the Python
    # attribute name.
    metadata_: Mapped[dict[str, Any]] = mapped_column("metadata", JSONB, nullable=False)
