"""ORM models for the `workspace-membership` capability (design D11-D13).

These are SQLAlchemy declarative models on the shared `app.db.Base` registry
(design D11) — a deliberate, confirmed deviation from `app/auth/session.py`'s
hand-written Core `Table` style (confirmed proposal decision 8). Column
shapes match the design's Interfaces/Contracts section exactly:

    app.workspace(id uuid pk, name text not null,
                  created_by_user_id uuid null fk app.app_user.id
                      on delete set null,
                  created_at timestamptz nn default now(),
                  updated_at timestamptz nn default now())

    app.workspace_member(id uuid pk,
                  workspace_id uuid nn fk app.workspace.id on delete cascade,
                  user_id uuid nn fk app.app_user.id on delete cascade,
                  joined_at timestamptz nn default now(),
                  CONSTRAINT uq_workspace_member_user_id UNIQUE (user_id))

    app.workspace_invite(id uuid pk,
                  workspace_id uuid nn fk app.workspace.id on delete cascade,
                  created_by_user_id uuid nn fk app.app_user.id
                      on delete cascade,
                  token_hash text nn unique, expires_at timestamptz nn,
                  accepted_at timestamptz null,
                  accepted_by_user_id uuid null fk app.app_user.id
                      on delete set null,
                  revoked_at timestamptz null,
                  created_at timestamptz nn default now())

`app.app_user` is referenced by table name only (`"app.app_user.id"`), never
by importing `app.auth.session` — that module's Core `Table` objects and
these declarative models are two independent definitions of the same
underlying `app_user` table, kept in sync only by the migration that creates
it (design D11's rationale for one shared `Base.metadata`: it lets THESE
models cross-reference each other, e.g. `app.account.workspace_id ->
app.workspace.id`, by string with no import cycle between sibling feature
packages; it does not extend to importing the pre-existing auth module).

Only the ORM shape lives here. `0002_workspace_accounts.py` is still a
hand-written `op.create_table` migration (design D11 rationale) — it is not
autogenerated from these classes, so a mismatch between the two must be
caught by `backend/tests/migrations/test_0002.py`, not by Alembic.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class Workspace(Base):
    __tablename__ = "workspace"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)


class WorkspaceMember(Base):
    __tablename__ = "workspace_member"
    __table_args__ = (UniqueConstraint("user_id", name="uq_workspace_member_user_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.workspace.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Decision 1 (exactly one workspace per user): enforced by the
    # `uq_workspace_member_user_id` unique constraint above, not by
    # application logic alone.
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="CASCADE"),
        nullable=False,
    )
    joined_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)


class WorkspaceInvite(Base):
    __tablename__ = "workspace_invite"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.workspace.id", ondelete="CASCADE"),
        nullable=False,
    )
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Design D12: the raw token is never stored — only its sha256 hexdigest.
    token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    expires_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    accepted_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    accepted_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app.app_user.id", ondelete="SET NULL"),
        nullable=True,
    )
    revoked_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
