"""workspace, membership, invites, and accounts

Creates the first product-domain tables for the `workspace-membership`,
`account-management`, and `account-visibility` capabilities (spec: Phase 1 —
Workspace, Users & Accounts; design D11-D20). This revision is hand-written
DDL, matching `0001_baseline.py`'s style exactly (`migrations/env.py`'s
`target_metadata` stays `None` — see `app/db.py`'s `Base` docstring, design
D11): it is not autogenerated from `app/workspace/models.py` /
`app/accounts/models.py`, so those ORM models and this migration must be
kept in sync by hand and are cross-checked by
`backend/tests/migrations/test_0002.py`.

Column shapes match the design's Interfaces/Contracts section exactly:

    app.workspace(id uuid pk, name text not null,
                  created_by_user_id uuid null fk app.app_user.id
                      on delete set null,
                  created_at timestamptz nn default now(),
                  updated_at timestamptz nn default now())

    app.workspace_member(id uuid pk,
                  workspace_id uuid nn fk app.workspace.id on delete cascade,
                  user_id uuid nn fk app.app_user.id on delete cascade,
                  joined_at timestamptz nn default now(),
                  CONSTRAINT uq_workspace_member_user_id UNIQUE (user_id))

    app.workspace_invite(id uuid pk,
                  workspace_id uuid nn fk app.workspace.id on delete cascade,
                  created_by_user_id uuid nn fk app.app_user.id
                      on delete cascade,
                  token_hash text nn unique, expires_at timestamptz nn,
                  accepted_at timestamptz null,
                  accepted_by_user_id uuid null fk app.app_user.id
                      on delete set null,
                  revoked_at timestamptz null,
                  created_at timestamptz nn default now())

    app.account(id uuid pk,
                workspace_id uuid nn fk app.workspace.id on delete cascade,
                owner_user_id uuid null fk app.app_user.id on delete restrict,
                name text nn, currency text nn,
                exchange_rate numeric(18,8) nn default 1,
                initial_funds numeric(18,2) nn default 0,
                is_personal boolean nn default false,
                archived boolean nn default false,
                created_at timestamptz nn default now(),
                updated_at timestamptz nn default now(),
                CHECK (currency ~ '^[A-Z]{3}$'),
                CHECK (exchange_rate > 0),
                CHECK (NOT is_personal OR owner_user_id IS NOT NULL))

`0001_baseline.py`'s `app.app_user` / `app.auth_session` tables are untouched
by this revision.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-07

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.create_table(
        "workspace",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema=SCHEMA,
    )

    op.create_table(
        "workspace_member",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("user_id", name="uq_workspace_member_user_id"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_workspace_member_workspace_id",
        "workspace_member",
        ["workspace_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "workspace_invite",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "accepted_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_workspace_invite_workspace_id",
        "workspace_invite",
        ["workspace_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "account",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "owner_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column(
            "exchange_rate",
            sa.Numeric(18, 8),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "initial_funds",
            sa.Numeric(18, 2),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "is_personal", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "archived", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name="ck_account_currency_iso4217"),
        sa.CheckConstraint("exchange_rate > 0", name="ck_account_exchange_rate_positive"),
        sa.CheckConstraint(
            "NOT is_personal OR owner_user_id IS NOT NULL",
            name="ck_account_personal_requires_owner",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_account_workspace_id",
        "account",
        ["workspace_id"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reverse creation order (design "Migration / Rollout"): drops account,
    # workspace_invite, workspace_member, workspace, in that order, leaving
    # 0001's app_user/auth_session tables completely untouched.
    op.drop_index("ix_account_workspace_id", table_name="account", schema=SCHEMA)
    op.drop_table("account", schema=SCHEMA)

    op.drop_index(
        "ix_workspace_invite_workspace_id", table_name="workspace_invite", schema=SCHEMA
    )
    op.drop_table("workspace_invite", schema=SCHEMA)

    op.drop_index(
        "ix_workspace_member_workspace_id", table_name="workspace_member", schema=SCHEMA
    )
    op.drop_table("workspace_member", schema=SCHEMA)

    op.drop_table("workspace", schema=SCHEMA)
