"""categories, transactions, and transaction category splits

Creates the Phase 2 product-domain tables for the `category-management`,
`transaction-management`, `transaction-splits`, and
`transaction-attachments` capabilities (spec: Phase 2 — Categories &
Manual Transactions; design D21, D28, D29, D30, D33). This revision is
hand-written DDL, matching `0002_workspace_accounts.py`'s style exactly
(`migrations/env.py`'s `target_metadata` stays `None` — see `app/db.py`'s
`Base` docstring, design D11): it is not autogenerated from
`app/categories/models.py` / `app/transactions/models.py`, so those ORM
models and this migration must be kept in sync by hand and are
cross-checked by `backend/tests/migrations/test_0003.py`.

Column shapes match the design's Interfaces/Contracts section exactly:

    app.category(id uuid pk,
        workspace_id uuid nn fk app.workspace.id on delete cascade,
        parent_id uuid null fk app.category.id on delete restrict,
        name text nn, icon text null, type text nn,
        created_at timestamptz nn default now(), updated_at timestamptz nn default now(),
        CHECK (type IN ('income','expense')),
        CHECK (parent_id IS NULL OR parent_id <> id))
    index: ix_category_workspace_id

    app.transaction(id uuid pk,
        workspace_id uuid nn fk app.workspace.id on delete cascade,
        account_id uuid nn fk app.account.id on delete cascade,
        type text nn, amount numeric(18,2) nn, occurred_on date nn, notes text null,
        is_refund boolean nn default false, checked boolean nn default false,
        photo_content_type text null, photo_uploaded_at timestamptz null,
        created_by_user_id uuid null fk app.app_user.id on delete set null,
        created_at timestamptz nn default now(), updated_at timestamptz nn default now(),
        CHECK (type IN ('income','expense')),
        CHECK (amount > 0),
        CHECK ((photo_content_type IS NULL) = (photo_uploaded_at IS NULL)))
    indexes: ix_transaction_workspace_id_occurred_on (workspace_id, occurred_on DESC),
             ix_transaction_account_id

    app.transaction_category_split(id uuid pk,
        transaction_id uuid nn fk app.transaction.id on delete cascade,
        category_id uuid nn fk app.category.id on delete restrict,
        amount numeric(18,2) nn,
        CHECK (amount > 0),
        UNIQUE (transaction_id, category_id))
    index: ix_transaction_category_split_category_id

`0001_baseline.py`'s `app.app_user` / `app.auth_session` tables and
`0002_workspace_accounts.py`'s `app.workspace` / `app.workspace_member` /
`app.workspace_invite` / `app.account` tables are untouched by this
revision.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-08

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.create_table(
        "category",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.category.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("type IN ('income', 'expense')", name="ck_category_type"),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name="ck_category_no_self_parent"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_category_workspace_id",
        "category",
        ["workspace_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "transaction",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.account.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_refund", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "checked", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("photo_content_type", sa.Text(), nullable=True),
        sa.Column("photo_uploaded_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("type IN ('income', 'expense')", name="ck_transaction_type"),
        sa.CheckConstraint("amount > 0", name="ck_transaction_amount_positive"),
        sa.CheckConstraint(
            "(photo_content_type IS NULL) = (photo_uploaded_at IS NULL)",
            name="ck_transaction_photo_pair",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transaction_workspace_id_occurred_on",
        "transaction",
        ["workspace_id", sa.text("occurred_on DESC")],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transaction_account_id",
        "transaction",
        ["account_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "transaction_category_split",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "transaction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.transaction.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "category_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.category.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.CheckConstraint(
            "amount > 0", name="ck_transaction_category_split_amount_positive"
        ),
        sa.UniqueConstraint(
            "transaction_id",
            "category_id",
            name="uq_transaction_category_split_txn_category",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transaction_category_split_category_id",
        "transaction_category_split",
        ["category_id"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reverse creation order (design "Migration / Rollout"): drops
    # transaction_category_split, transaction, category, in that order,
    # leaving 0002's workspace/account tables and 0001's auth tables
    # completely untouched.
    op.drop_index(
        "ix_transaction_category_split_category_id",
        table_name="transaction_category_split",
        schema=SCHEMA,
    )
    op.drop_table("transaction_category_split", schema=SCHEMA)

    op.drop_index("ix_transaction_account_id", table_name="transaction", schema=SCHEMA)
    op.drop_index(
        "ix_transaction_workspace_id_occurred_on", table_name="transaction", schema=SCHEMA
    )
    op.drop_table("transaction", schema=SCHEMA)

    op.drop_index("ix_category_workspace_id", table_name="category", schema=SCHEMA)
    op.drop_table("category", schema=SCHEMA)
