"""transfers

Creates the Phase 3 `app.transfer` table for the `transfer-management`
capability (spec: Phase 3 — Transfers Between Accounts; design D36-D42).
This revision is hand-written DDL, matching
`0002_workspace_accounts.py`/`0003_categories_transactions.py`'s style
exactly (`migrations/env.py`'s `target_metadata` stays `None` — see
`app/db.py`'s `Base` docstring, design D11): it is not autogenerated from
`app/transfers/models.py`, so that ORM model and this migration must be
kept in sync by hand and are cross-checked by
`backend/tests/migrations/test_0004.py`.

Column shape matches the design's Interfaces/Contracts section exactly:

    app.transfer(id uuid pk,
        workspace_id     uuid nn fk app.workspace.id on delete cascade,
        from_account_id  uuid nn fk app.account.id   on delete NO ACTION,   -- D36
        to_account_id    uuid nn fk app.account.id   on delete NO ACTION,   -- D36
        from_amount numeric(18,2) nn, to_amount numeric(18,2) nn,           -- D37
        occurred_on date nn, notes text null,
        created_by_user_id uuid null fk app.app_user.id on delete set null,
        created_at timestamptz nn default now(), updated_at timestamptz nn default now(),
        CONSTRAINT ck_transfer_from_amount_positive  CHECK (from_amount > 0),
        CONSTRAINT ck_transfer_to_amount_positive    CHECK (to_amount > 0),
        CONSTRAINT ck_transfer_distinct_accounts     CHECK (from_account_id <> to_account_id))
    indexes: ix_transfer_workspace_id_occurred_on (workspace_id, occurred_on DESC),
             ix_transfer_from_account_id, ix_transfer_to_account_id

Two SEPARATE single-column account indexes, not a composite: design D39's
account filter is `sa.or_(from_account_id == x, to_account_id == x)`,
which Postgres serves with a BitmapOr over two independent indexes — a
composite `(from_account_id, to_account_id)` index cannot answer an OR.

`ON DELETE NO ACTION` (not `RESTRICT`) on both account FKs is load-bearing
(design D36): `transfer.workspace_id`/`account.workspace_id` are both
CASCADE from `app.workspace`, and Postgres fires a deleted parent's
referential-action triggers across referencing tables in UNSPECIFIED
order. `RESTRICT` checks immediately, so a workspace delete that happens
to cascade `account` before `transfer` would error out. `NO ACTION`
checks at end-of-statement, so the workspace→transfer cascade has
already removed the rows by the time the check runs — an identical
blocking guarantee for a direct account delete (no application path
exists to delete one — Phase 1 D6), with no ordering trap on workspace
teardown. Proved empirically, not just asserted, in
`backend/tests/migrations/test_0004.py` (design RED #16).

`0001_baseline.py`, `0002_workspace_accounts.py`, and
`0003_categories_transactions.py`'s tables are untouched by this
revision.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.create_table(
        "transfer",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "from_account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.account.id", ondelete="NO ACTION"),
            nullable=False,
        ),
        sa.Column(
            "to_account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.account.id", ondelete="NO ACTION"),
            nullable=False,
        ),
        sa.Column("from_amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("to_amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("from_amount > 0", name="ck_transfer_from_amount_positive"),
        sa.CheckConstraint("to_amount > 0", name="ck_transfer_to_amount_positive"),
        sa.CheckConstraint(
            "from_account_id <> to_account_id", name="ck_transfer_distinct_accounts"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transfer_workspace_id_occurred_on",
        "transfer",
        ["workspace_id", sa.text("occurred_on DESC")],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transfer_from_account_id",
        "transfer",
        ["from_account_id"],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transfer_to_account_id",
        "transfer",
        ["to_account_id"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reverse creation order (design "Migration / Rollout"): drop the
    # three indexes, then the table, leaving 0003/0002/0001's tables and
    # rows completely untouched.
    op.drop_index("ix_transfer_to_account_id", table_name="transfer", schema=SCHEMA)
    op.drop_index("ix_transfer_from_account_id", table_name="transfer", schema=SCHEMA)
    op.drop_index(
        "ix_transfer_workspace_id_occurred_on", table_name="transfer", schema=SCHEMA
    )
    op.drop_table("transfer", schema=SCHEMA)
