"""templates_and_recurring

Creates the Phase 4 `app.transaction_template`, `app.transaction_template_split`,
`app.recurring_transaction`, `app.recurring_transaction_split`, and
`app.recurring_occurrence` tables for the `transaction-templates` and
`recurring-transactions` capabilities (spec: Phase 4 — Recurring & Scheduled
Transactions; design D45-D56). This revision is hand-written DDL, matching
`0002_workspace_accounts.py`/`0003_categories_transactions.py`/
`0004_transfers.py`'s style exactly (`migrations/env.py`'s `target_metadata`
stays `None` — see `app/db.py`'s `Base` docstring, design D11): it is not
autogenerated from `app/templates/models.py`/`app/recurring/models.py`, so
those ORM models and this migration must be kept in sync by hand and are
cross-checked by `backend/tests/migrations/test_0005.py`.

Column shapes match the design's Interfaces/Contracts section exactly:

    app.transaction_template(id uuid pk,
        workspace_id uuid nn fk app.workspace.id on delete cascade,
        account_id   uuid nn fk app.account.id   on delete cascade,
        name text nn, position integer nn default 0,
        type text nn, amount numeric(18,2) nn, notes text null,
        created_by_user_id uuid nn fk app.app_user.id on delete cascade,
        created_at/updated_at timestamptz nn default now(),
        CHECK (type IN ('income','expense')), CHECK (amount > 0),
        UNIQUE (workspace_id, name))
    index: ix_transaction_template_workspace_id_position (workspace_id, position)

    app.transaction_template_split(id uuid pk,
        template_id uuid nn fk app.transaction_template.id on delete cascade,
        category_id uuid nn fk app.category.id on delete restrict,       -- D28/D55
        amount numeric(18,2) nn, CHECK (amount > 0),
        UNIQUE (template_id, category_id))

    app.recurring_transaction(id uuid pk,
        workspace_id uuid nn fk app.workspace.id on delete cascade,
        account_id   uuid nn fk app.account.id   on delete cascade,
        type text nn, amount numeric(18,2) nn, notes text null,
        is_refund boolean nn default false, is_subscription boolean nn default false,
        repeat_every integer nn, period text nn,
        starts_on date nn,
        occurrence_index integer nn default 0,
        next_date date nn,
        ends_on date null, reminder_days_before integer null,
        last_reminded_for_date date null, reminder_locale text nn default 'en',
        created_by_user_id uuid nn fk app.app_user.id on delete CASCADE,     -- D50
        created_at/updated_at timestamptz nn default now(),
        CHECK (type IN ('income','expense')), CHECK (amount > 0),
        CHECK (repeat_every >= 1), CHECK (period IN ('day','week','month','year')),
        CHECK (occurrence_index >= 0), CHECK (ends_on IS NULL OR ends_on >= starts_on),
        CHECK (reminder_days_before IS NULL OR reminder_days_before BETWEEN 0 AND 30),
        CHECK (reminder_locale IN ('en','es')))
    indexes: ix_recurring_transaction_next_date (next_date)     -- the ONE deliberately
                                                                 -- non-workspace-prefixed
                                                                 -- index (design D51's
                                                                 -- Data Flow ①: the due
                                                                 -- scan is cross-workspace
                                                                 -- by design)
             ix_recurring_transaction_workspace_id, ix_recurring_transaction_account_id

    app.recurring_transaction_split(id uuid pk,
        recurring_transaction_id uuid nn fk app.recurring_transaction.id on delete cascade,
        category_id uuid nn fk app.category.id on delete restrict,
        amount numeric(18,2) nn, CHECK (amount > 0),
        UNIQUE (recurring_transaction_id, category_id))

    app.recurring_occurrence(
        recurring_transaction_id uuid nn fk app.recurring_transaction.id on delete cascade,
        occurrence_date date nn,
        transaction_id uuid null fk app.transaction.id on delete SET NULL,   -- tombstone
                                                                              -- survives a
                                                                              -- delete (D47)
        generated_at timestamptz nn default now(),
        PRIMARY KEY (recurring_transaction_id, occurrence_date))
    index: ix_recurring_occurrence_transaction_id (transaction_id)

D55: two small mirrored split tables (`transaction_template_split`,
`recurring_transaction_split`) rather than one polymorphic split table — a
polymorphic parent cannot carry a real foreign key, which would trade D28's
enforced "a category referenced by an allocation cannot be deleted" for an
application-level check.

`recurring_occurrence` is created here, in the SAME migration as the CRUD
tables, even though the write path that populates it
(`app.recurring.generation`) is PR2's job — the proposal's own File Changes
table places all five tables in this one migration batch (design "Migration
/ Rollout": "creates five tables plus indexes"), so the schema is not split
across two Alembic revisions for one phase.

`0001_baseline.py`, `0002_workspace_accounts.py`,
`0003_categories_transactions.py`, and `0004_transfers.py`'s tables are
untouched by this revision — no `ALTER` against any of them.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.create_table(
        "transaction_template",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.account.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "type IN ('income', 'expense')", name="ck_transaction_template_type"
        ),
        sa.CheckConstraint("amount > 0", name="ck_transaction_template_amount_positive"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_transaction_template_workspace_name"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transaction_template_workspace_id_position",
        "transaction_template",
        ["workspace_id", "position"],
        schema=SCHEMA,
    )

    op.create_table(
        "transaction_template_split",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "template_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.transaction_template.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "category_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.category.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.CheckConstraint(
            "amount > 0", name="ck_transaction_template_split_amount_positive"
        ),
        sa.UniqueConstraint(
            "template_id", "category_id", name="uq_transaction_template_split_template_category"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transaction_template_split_category_id",
        "transaction_template_split",
        ["category_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "recurring_transaction",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.account.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_refund", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_subscription", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("repeat_every", sa.Integer(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("occurrence_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("next_date", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("reminder_days_before", sa.Integer(), nullable=True),
        sa.Column("last_reminded_for_date", sa.Date(), nullable=True),
        sa.Column("reminder_locale", sa.Text(), nullable=False, server_default="en"),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "type IN ('income', 'expense')", name="ck_recurring_transaction_type"
        ),
        sa.CheckConstraint("amount > 0", name="ck_recurring_transaction_amount_positive"),
        sa.CheckConstraint(
            "repeat_every >= 1", name="ck_recurring_transaction_repeat_every_positive"
        ),
        sa.CheckConstraint(
            "period IN ('day', 'week', 'month', 'year')",
            name="ck_recurring_transaction_period",
        ),
        sa.CheckConstraint(
            "occurrence_index >= 0", name="ck_recurring_transaction_occurrence_index_non_negative"
        ),
        sa.CheckConstraint(
            "ends_on IS NULL OR ends_on >= starts_on",
            name="ck_recurring_transaction_ends_on_after_starts_on",
        ),
        sa.CheckConstraint(
            "reminder_days_before IS NULL OR reminder_days_before BETWEEN 0 AND 30",
            name="ck_recurring_transaction_reminder_days_before_range",
        ),
        sa.CheckConstraint(
            "reminder_locale IN ('en', 'es')", name="ck_recurring_transaction_reminder_locale"
        ),
        schema=SCHEMA,
    )
    # Deliberately NOT workspace-prefixed (design D51's Data Flow ①): the
    # scheduled generation run's due-detection scan is cross-workspace by
    # design, so this index is shaped for that scan, not for a per-workspace
    # list.
    op.create_index(
        "ix_recurring_transaction_next_date",
        "recurring_transaction",
        ["next_date"],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_recurring_transaction_workspace_id",
        "recurring_transaction",
        ["workspace_id"],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_recurring_transaction_account_id",
        "recurring_transaction",
        ["account_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "recurring_transaction_split",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "recurring_transaction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.recurring_transaction.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "category_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.category.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.CheckConstraint(
            "amount > 0", name="ck_recurring_transaction_split_amount_positive"
        ),
        sa.UniqueConstraint(
            "recurring_transaction_id",
            "category_id",
            name="uq_recurring_transaction_split_recurring_category",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_recurring_transaction_split_category_id",
        "recurring_transaction_split",
        ["category_id"],
        schema=SCHEMA,
    )

    op.create_table(
        "recurring_occurrence",
        sa.Column(
            "recurring_transaction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.recurring_transaction.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column(
            "transaction_id",
            postgresql.UUID(as_uuid=True),
            # D47: SET NULL, not CASCADE — a user-deleted generated
            # transaction leaves this row as a tombstone so generation
            # never resurrects it.
            sa.ForeignKey(f"{SCHEMA}.transaction.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "generated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint(
            "recurring_transaction_id", "occurrence_date", name="pk_recurring_occurrence"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_recurring_occurrence_transaction_id",
        "recurring_occurrence",
        ["transaction_id"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reverse creation order (design "Migration / Rollout"): drop indexes
    # then tables, leaving 0004/0003/0002/0001's tables and rows completely
    # untouched.
    op.drop_index(
        "ix_recurring_occurrence_transaction_id",
        table_name="recurring_occurrence",
        schema=SCHEMA,
    )
    op.drop_table("recurring_occurrence", schema=SCHEMA)

    op.drop_index(
        "ix_recurring_transaction_split_category_id",
        table_name="recurring_transaction_split",
        schema=SCHEMA,
    )
    op.drop_table("recurring_transaction_split", schema=SCHEMA)

    op.drop_index(
        "ix_recurring_transaction_account_id", table_name="recurring_transaction", schema=SCHEMA
    )
    op.drop_index(
        "ix_recurring_transaction_workspace_id", table_name="recurring_transaction", schema=SCHEMA
    )
    op.drop_index(
        "ix_recurring_transaction_next_date", table_name="recurring_transaction", schema=SCHEMA
    )
    op.drop_table("recurring_transaction", schema=SCHEMA)

    op.drop_index(
        "ix_transaction_template_split_category_id",
        table_name="transaction_template_split",
        schema=SCHEMA,
    )
    op.drop_table("transaction_template_split", schema=SCHEMA)

    op.drop_index(
        "ix_transaction_template_workspace_id_position",
        table_name="transaction_template",
        schema=SCHEMA,
    )
    op.drop_table("transaction_template", schema=SCHEMA)
