"""budgets

Creates the Phase 5 `app.budget` table for the `budget-management`
capability (spec: Phase 5 — Budgets; design D66-D70). This revision is
hand-written DDL, matching `0002_workspace_accounts.py`/
`0003_categories_transactions.py`/`0004_transfers.py`/
`0005_templates_and_recurring.py`'s style exactly (`migrations/env.py`'s
`target_metadata` stays `None` — see `app/db.py`'s `Base` docstring,
design D11): it is not autogenerated from `app/budgets/models.py`, so that
ORM model and this migration must be kept in sync by hand and are
cross-checked by `backend/tests/migrations/test_0006.py`.

Column shape matches the design's Interfaces/Contracts section exactly:

    app.budget(id uuid pk,
        workspace_id uuid nn fk app.workspace.id on delete cascade,
        category_id  uuid nn fk app.category.id  on delete restrict,     -- D67
        account_id   uuid null fk app.account.id on delete cascade,      -- D68
        name text null,
        amount numeric(18,2) nn,
        currency text nn,
        created_at/updated_at timestamptz nn default now(),
        CHECK (amount > 0),                    -- ck_budget_amount_positive
        CHECK (currency ~ '^[A-Z]{3}$'))       -- ck_budget_currency_iso4217
    indexes: ix_budget_workspace_id, ix_budget_category_id

D66: mirrors `Account.currency`'s exact ISO-4217 CHECK. D67: `category_id`
is `ON DELETE RESTRICT` — matches every other category reference in the
codebase (D28); deletion of a still-referenced category is blocked with a
409, not silently cascaded or orphaned. D68: `account_id` is
`ON DELETE CASCADE`, not `SET NULL` — a `SET NULL` would silently widen
an account-scoped budget into an all-accounts budget, which D68 rejects
as actively harmful; deleting the watched account deletes the budget
that only existed to watch it. D69: deliberately NO uniqueness constraint
over `(workspace_id, category_id, account_id)` — plain SQL UNIQUE does not
dedupe NULL `account_id`, and duplicate budgets on the same scope are
legal (different currencies, different labels).

`0001_baseline.py` through `0005_templates_and_recurring.py`'s tables are
untouched by this revision — no `ALTER` against any of them.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-13

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.create_table(
        "budget",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "category_id",
            postgresql.UUID(as_uuid=True),
            # D67: RESTRICT — matches every other category reference
            # (D28); a still-referenced category cannot be deleted.
            sa.ForeignKey(f"{SCHEMA}.category.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            postgresql.UUID(as_uuid=True),
            # D68: CASCADE, not SET NULL — deleting the watched account
            # deletes the budget scoped to it, rather than silently
            # widening it into an all-accounts budget.
            sa.ForeignKey(f"{SCHEMA}.account.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("amount > 0", name="ck_budget_amount_positive"),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name="ck_budget_currency_iso4217"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_budget_workspace_id",
        "budget",
        ["workspace_id"],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_budget_category_id",
        "budget",
        ["category_id"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reverse creation order, leaving 0005/0004/0003/0002/0001's tables
    # and rows completely untouched.
    op.drop_index("ix_budget_category_id", table_name="budget", schema=SCHEMA)
    op.drop_index("ix_budget_workspace_id", table_name="budget", schema=SCHEMA)
    op.drop_table("budget", schema=SCHEMA)
