"""workspace roles

Adds owner/member distinction to `app.workspace_member` for the
`workspace-roles` domain (spec: Phase 8 — Admin, workspace-roles domain;
design D93/D94). This revision is hand-written DDL, matching
`0002_workspace_accounts.py` through `0006_budgets.py`'s style exactly
(`migrations/env.py`'s `target_metadata` stays `None` — see `app/db.py`'s
`Base` docstring, design D11): it is not autogenerated from
`app/workspace/models.py`, so that ORM model and this migration must be
kept in sync by hand and are cross-checked by
`backend/tests/migrations/test_0007.py`.

Column shape matches the design's Interfaces/Contracts section exactly:

    app.workspace_member.role text not null default 'member'
        CONSTRAINT ck_workspace_member_role CHECK (role IN ('owner','member'))

Design D93: TEXT + CHECK, not a native PG enum — matches the repo's
existing convention (hand-written migrations, `Text`-typed role/status
columns elsewhere) and keeps the migration trivially reversible; a native
PG enum needs its own `CREATE TYPE`/`DROP TYPE` and makes adding a value
later an `ALTER TYPE` that cannot run inside some transaction contexts.

Design D94: after the column is added, three ordered steps run inside
this same `upgrade()`, in the SAME transaction Alembic already wraps each
revision in:

1. The membership row matching `Workspace.created_by_user_id` becomes
   `owner`.
2. Fallback: for any workspace still without an owner after step 1 (the
   creator's own membership row is missing — e.g. `created_by_user_id`
   went NULL via its `ON DELETE SET NULL`, or the creator already left),
   the member with the earliest `joined_at` (tie-broken by `id` for
   determinism) is promoted.
3. Assertion: every workspace must end with EXACTLY ONE owner (`== 1`,
   not `>= 1` — design confirms strictly single-owner per O4). If any
   workspace fails this, `upgrade()` raises `RuntimeError` naming the
   offending workspace ids, which aborts Alembic's transaction and rolls
   the whole migration back — loud beats silent. The one case this
   legitimately catches: a workspace with ZERO member rows, which step 2
   cannot fix (there is nobody to promote). That is a genuinely
   unadministrable orphan and the migration SHOULD fail rather than paper
   over it.

`downgrade()` drops the CHECK constraint then the column — no data-loss
concern; dropping `role` restores today's flat symmetric membership,
which is strictly MORE permissive (nobody loses access on rollback).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-14

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.add_column(
        "workspace_member",
        sa.Column("role", sa.Text(), nullable=False, server_default="member"),
        schema=SCHEMA,
    )
    op.create_check_constraint(
        "ck_workspace_member_role",
        "workspace_member",
        "role IN ('owner', 'member')",
        schema=SCHEMA,
    )

    bind = op.get_bind()

    # Step 1 (D94): the membership row matching the workspace's creator
    # becomes owner.
    bind.execute(
        sa.text(
            "UPDATE app.workspace_member m SET role = 'owner' "
            "FROM app.workspace w "
            "WHERE m.workspace_id = w.id AND w.created_by_user_id = m.user_id"
        )
    )

    # Step 2 (D94): fallback to the earliest-joined member (tie-broken by
    # id) for any workspace that still has no owner after step 1.
    bind.execute(
        sa.text(
            "UPDATE app.workspace_member SET role = 'owner' "
            "WHERE id IN ("
            "  SELECT DISTINCT ON (wm.workspace_id) wm.id "
            "  FROM app.workspace_member wm "
            "  WHERE wm.workspace_id NOT IN ("
            "    SELECT workspace_id FROM app.workspace_member WHERE role = 'owner'"
            "  ) "
            "  ORDER BY wm.workspace_id, wm.joined_at, wm.id"
            ")"
        )
    )

    # Step 3 (D94): every workspace MUST end with exactly one owner.
    # Zero-member workspaces (no row to promote in step 2) and any other
    # backfill failure surface here rather than being silently skipped.
    offenders = bind.execute(
        sa.text(
            "SELECT w.id AS id, count(m.id) FILTER (WHERE m.role = 'owner') AS owners "
            "FROM app.workspace w "
            "LEFT JOIN app.workspace_member m ON m.workspace_id = w.id "
            "GROUP BY w.id "
            "HAVING count(m.id) FILTER (WHERE m.role = 'owner') <> 1"
        )
    ).fetchall()
    if offenders:
        offending_ids = ", ".join(str(row.id) for row in offenders)
        raise RuntimeError(
            "workspace role backfill failed: the following workspace ids do not "
            f"have exactly one owner after backfill: {offending_ids}"
        )


def downgrade() -> None:
    op.drop_constraint(
        "ck_workspace_member_role", "workspace_member", schema=SCHEMA, type_="check"
    )
    op.drop_column("workspace_member", "role", schema=SCHEMA)
