"""platform admin

Adds `app.platform_admin` for the `platform-admin` domain (spec: Phase 8 —
Admin, platform-admin domain; design D97). Hand-written DDL, matching
`0002_workspace_accounts.py` through `0007_workspace_roles.py`'s style
exactly (`migrations/env.py`'s `target_metadata` stays `None`) — this is
not autogenerated from `app/admin/models.py`, so that ORM model and this
migration must be kept in sync by hand and are cross-checked by
`backend/tests/migrations/test_0008.py`.

Column shape matches design's Interfaces/Contracts section exactly:

    app.platform_admin(
      user_id uuid PRIMARY KEY REFERENCES app.app_user(id) ON DELETE CASCADE,
      granted_at timestamptz NOT NULL,
      granted_by_user_id uuid NULL REFERENCES app.app_user(id)
          ON DELETE SET NULL,
      note text NULL)

Design D97: `user_id` is the PRIMARY KEY directly, not a surrogate `id`
plus a separate unique constraint — "at most one grant per user" is a
structural fact this way, not a constraint someone must remember to keep
in place. `granted_by_user_id` is nullable with `ON DELETE SET NULL` —
deliberately never CASCADE — for two distinct reasons: NULL means
bootstrap (no human granter existed, see design D107/`0009`), and a
granter whose own account is later removed must not cascade-delete the
grant of the person THEY granted; provenance for the grantee's row must
survive the granter's account changes. `user_id` itself IS `ON DELETE
CASCADE`: a nonexistent user holding platform admin is meaningless.
Revoke is a hard `DELETE` of this row elsewhere (Unit 3) — the audit
trail, not this table, is the history of past grants/revokes.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-14

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def upgrade() -> None:
    op.create_table(
        "platform_admin",
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "granted_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "granted_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Dropping `platform_admin` closes the cross-workspace authority path
    # entirely — the safe failure direction (design "Migration / Rollout").
    op.drop_table("platform_admin", schema=SCHEMA)
