"""audit log

Adds `app.audit_log` for the `audit-log` domain (spec: Phase 8 — Admin,
audit-log domain; design D102). Hand-written DDL, matching
`0002_workspace_accounts.py` through `0010_admin_capability_columns.py`'s
style exactly (`migrations/env.py`'s `target_metadata` stays `None`) — not
autogenerated from `app/audit/models.py`, so that ORM model and this
migration must be kept in sync by hand and are cross-checked by
`backend/tests/migrations/test_0011.py`.

Column shape matches design's Interfaces/Contracts section exactly:

    app.audit_log(
      id uuid PRIMARY KEY,
      created_at timestamptz NOT NULL,
      actor_user_id uuid NULL REFERENCES app.app_user(id) ON DELETE SET NULL,
      actor_was_platform_admin boolean NOT NULL,
      action text NOT NULL,             -- CHECK against the action catalog
      target_type text NOT NULL,
      target_id uuid NULL,
      workspace_id uuid NULL REFERENCES app.workspace(id) ON DELETE SET NULL,
      metadata jsonb NOT NULL DEFAULT '{}'::jsonb)
    INDEX ix_audit_log_workspace_created ON (workspace_id, created_at DESC)
    INDEX ix_audit_log_actor_created     ON (actor_user_id, created_at DESC)

Design D102: no `updated_at`, no `deleted_at`, no soft-delete column —
append-only is expressed by the absence of any mutation path, and
`app/audit/models.py` exposes no update/delete helper. `actor_was_platform_
admin` is a snapshot boolean because platform-admin grants are revocable:
reconstructing "was this person an admin then?" from the current
`platform_admin` table is impossible after a revoke. Both FKs are
`ON DELETE SET NULL`, never CASCADE — an audit row must survive the
deletion of its subject or the trail could be erased by deleting the
evidence's own referent. `workspace_id` is nullable: platform-level
actions (grant admin, deactivate user) belong to no single workspace; that
nullability is also what makes the O3 owner-read rule work (design D105) —
a single `workspace_id = :caller_workspace_id` predicate.

The CHECK constraint on `action` enumerates exactly the catalog in
`app/audit/actions.py`'s `AuditAction` StrEnum, so a typo'd action string
is a DB error, not a silently unqueryable row (design D103). Deliberately
EXCLUDES `workspace.member_left` from design D103's original catalog: the
confirmed spec requirement ("Self-Removal Is a Distinct Path", audit-log
domain's "Self-removal not audited" scenario) states self-removal MUST
NOT be audited, which conflicts with design D104's table entry pairing
`leave_workspace` with a `workspace.member_left` action. Spec is the
acceptance-criteria authority here, so this migration's CHECK constraint
(and the whole call-site wiring) follows the spec, not that one design
table row — see apply-progress for the recorded deviation.

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-15

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"

# Must match `app/audit/actions.py`'s `AuditAction` StrEnum exactly.
_AUDIT_ACTIONS = (
    "workspace.renamed",
    "workspace.member_removed",
    "workspace.invite_generated",
    "workspace.invite_revoked",
    "workspace.ownership_transferred",
    "platform.user_deactivated",
    "platform.user_reactivated",
    "platform.workspace_deactivated",
    "platform.workspace_reactivated",
    "platform.admin_granted",
    "platform.admin_revoked",
    "platform.admin_self_revoked",
)


def upgrade() -> None:
    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "actor_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.app_user.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("actor_was_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.workspace.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.CheckConstraint(
            "action IN ({})".format(", ".join(f"'{action}'" for action in _AUDIT_ACTIONS)),
            name="ck_audit_log_action",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_audit_log_workspace_created",
        "audit_log",
        ["workspace_id", sa.text("created_at DESC")],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_audit_log_actor_created",
        "audit_log",
        ["actor_user_id", sa.text("created_at DESC")],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Dropping `audit_log` loses audit history on rollback — accepted per
    # design's "Migration / Rollout": no feature treats it as a source of
    # truth, and no Phase 0-10 table depends on it.
    op.drop_index("ix_audit_log_actor_created", table_name="audit_log", schema=SCHEMA)
    op.drop_index("ix_audit_log_workspace_created", table_name="audit_log", schema=SCHEMA)
    op.drop_table("audit_log", schema=SCHEMA)
