"""ocr drafts

Adds `app.transaction.ocr_status` and `app.transaction_ocr_extraction` for
Phase 9 (Photo-Based Expense Capture / OCR), design D115-D117. Hand-written
DDL, matching `0002_workspace_accounts.py` through `0011_audit_log.py`'s
style exactly (`migrations/env.py`'s `target_metadata` stays `None`) — not
autogenerated from `app/transactions/models.py`, so that ORM model and this
migration must be kept in sync by hand and are cross-checked by
`backend/tests/migrations/test_0012.py`.

Judgment call (Unit 1 apply): tasks.md/design were drafted naming this
migration `0009_ocr_drafts.py`, but `0009`-`0011` were consumed by Phase 8
(bootstrap platform admin, admin capability columns, audit log) before this
unit landed. This migration is therefore `0012`, chained onto the real head
(`0011`) rather than the filename the design text assumed — the numbering
scheme itself (sequential, chained via `down_revision`) is unchanged.

Column shape matches design's D115/D117 exactly:

    app.transaction.ocr_status text NULL
      CHECK (ocr_status IS NULL OR ocr_status IN
             ('pending_ocr','extracted','extraction_failed','confirmed'))
    INDEX ix_transaction_ocr_status ON (workspace_id, ocr_status)
      WHERE ocr_status IS NOT NULL

    app.transaction_ocr_extraction(
      transaction_id uuid PRIMARY KEY
          REFERENCES app.transaction(id) ON DELETE CASCADE,
      status               text        NOT NULL,   -- 'succeeded' | 'failed'
      failure_reason       text        NULL,
      extracted_amount     numeric(18,2) NULL,
      extracted_occurred_on date       NULL,
      extracted_vendor_name text       NULL,
      extracted_currency   text        NULL,       -- advisory only (D118)
      field_confidence     jsonb       NOT NULL DEFAULT '{}'::jsonb,
      raw_response         jsonb       NULL,
      provider             text        NOT NULL DEFAULT 'textract',
      attempt_count        smallint    NOT NULL DEFAULT 1,
      created_at           timestamptz NOT NULL,
      CHECK (status IN ('succeeded','failed')),
      CHECK ((status = 'failed') = (failure_reason IS NOT NULL)),
      CHECK (failure_reason IS NULL OR failure_reason IN
             ('provider_unavailable','unreadable_document','no_receipt_detected')))

`ocr_status` is nullable with no backfill (design D115): a pure additive
column against the existing ~all-NULL corpus. `transaction_id` is the PK of
`transaction_ocr_extraction` (not a surrogate `id`), making the 1:1
relationship structural — design D117, mirroring the existing
`platform_admin.user_id` precedent. The `(status='failed') = (failure_reason
IS NOT NULL)` paired CHECK is the same idiom as
`ck_transaction_photo_pair` in `0003_categories_transactions.py`.
`raw_response` holds real receipt contents and must never be logged or
returned by any API — enforced at the application layer in later units, not
here; this migration only shapes the column.

Rollback (design "Migration / Rollout"): downgrade must delete every
non-confirmed draft transaction BEFORE dropping `ocr_status`, or a rollback
would silently publish `amount=0.01` sentinel rows into the user's ledger as
ordinary transactions. `transaction_ocr_extraction` rows cascade-delete with
their owning draft; any leftover extraction rows for `confirmed`
transactions are dropped along with the table itself.

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-15

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"

_OCR_STATUSES = ("pending_ocr", "extracted", "extraction_failed", "confirmed")
_EXTRACTION_STATUSES = ("succeeded", "failed")
_FAILURE_REASONS = ("provider_unavailable", "unreadable_document", "no_receipt_detected")


def upgrade() -> None:
    op.add_column(
        "transaction",
        sa.Column("ocr_status", sa.Text(), nullable=True),
        schema=SCHEMA,
    )
    op.create_check_constraint(
        "ck_transaction_ocr_status",
        "transaction",
        "ocr_status IS NULL OR ocr_status IN ({})".format(
            ", ".join(f"'{status}'" for status in _OCR_STATUSES)
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_transaction_ocr_status",
        "transaction",
        ["workspace_id", "ocr_status"],
        schema=SCHEMA,
        postgresql_where=sa.text("ocr_status IS NOT NULL"),
    )

    op.create_table(
        "transaction_ocr_extraction",
        sa.Column(
            "transaction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{SCHEMA}.transaction.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("extracted_amount", sa.Numeric(18, 2), nullable=True),
        sa.Column("extracted_occurred_on", sa.Date(), nullable=True),
        sa.Column("extracted_vendor_name", sa.Text(), nullable=True),
        sa.Column("extracted_currency", sa.Text(), nullable=True),
        sa.Column(
            "field_confidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "provider", sa.Text(), nullable=False, server_default=sa.text("'textract'")
        ),
        sa.Column(
            "attempt_count", sa.SmallInteger(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "status IN ({})".format(", ".join(f"'{s}'" for s in _EXTRACTION_STATUSES)),
            name="ck_ocr_extraction_status",
        ),
        sa.CheckConstraint(
            "(status = 'failed') = (failure_reason IS NOT NULL)",
            name="ck_ocr_extraction_failure_reason",
        ),
        sa.CheckConstraint(
            "failure_reason IS NULL OR failure_reason IN ({})".format(
                ", ".join(f"'{r}'" for r in _FAILURE_REASONS)
            ),
            name="ck_ocr_extraction_failure_reason_domain",
        ),
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Draft rows use the amount=0.01 sentinel (design D119) — a rollback
    # must remove every non-confirmed draft BEFORE the column drops, or the
    # sentinel silently becomes an ordinary transaction (design "Migration
    # / Rollout"). transaction_ocr_extraction rows cascade-delete with them.
    op.execute(
        f"DELETE FROM {SCHEMA}.transaction "
        "WHERE ocr_status IS NOT NULL AND ocr_status <> 'confirmed'"
    )
    op.drop_table("transaction_ocr_extraction", schema=SCHEMA)
    op.drop_index("ix_transaction_ocr_status", table_name="transaction", schema=SCHEMA)
    op.drop_constraint("ck_transaction_ocr_status", "transaction", schema=SCHEMA)
    op.drop_column("transaction", "ocr_status", schema=SCHEMA)
